package com.illuminart.geoanalysis;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
public class GeoAnalysisApplication {

	public static void main(String[] args) {
		SpringApplication.run(GeoAnalysisApplication.class, args);
	}

}
